resources:
- mutating-webhook-config.yaml
- validating-webhook-config.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: europe-docker.pkg.dev/gardener-project/public/gardener/kupid
  newTag: v0.6.0-dev
