apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kupid
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: kupid
      path: /webhook
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: mutate.kupid.gardener.cloud
  namespaceSelector:
    matchExpressions:
    - key: role
      operator: NotIn
      values: [ "kube-system" ] 
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicationcontrollers
  - apiGroups:
    - "apps"
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
    - deployments
  #  - replicasets
    - statefulsets
  - apiGroups:
    - "batch"
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
  - apiGroups:
    - "batch"
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None
  timeoutSeconds: 30
