image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/kupid
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

logging:
  level: info

resources:
  requests:
    cpu: 100m
    memory: 64M
  limits:
    cpu: 200m
    memory: 256M

vpa:
  enabled: true
  minAllowed:
    cpu: 100m
    memory: 64M
  updatePolicy:
    updateMode: "Auto"

manager:
  qps: 5.0
  burst: 10

webhookConfig:
  serverPort: 9443
  timeoutSeconds: 15
  failurePolicy: Ignore

healthPort: 8080
metricsPort: 8081

enableLeaderElection: true

# policies:
#   etcd:
#     namespaceLabels: {}
#     podLabels:
#       app: etcd-statefulset
#       role: main
#     podExpressions:
#     - key: networking.resources.gardener.cloud/to-etcd-main-client-tcp-2379
#       operator: DoesNotExist
#     nodeLabels:
#       pool.worker.gardener.cloud/dedicated-for: etcd
#     tolerations:
#     - key: pool.worker.gardener.cloud/dedicated-for
#       operator: Equal
#       value: etcd
#       effect: NoExecute
#   fluent-bit:
#     namespaceLabels: {}
#     podLabels:
#       app: fluent-bit
#       role: logging
#       gardener.cloud/role: logging
#     tolerations:
#     - key: pool.worker.gardener.cloud/dedicated-for
#       operator: Equal
#       value: etcd
#       effect: NoExecute

gardener:
  version: ""
