image:
  repository: eu.gcr.io/gardener-project/gardener/kupid
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

logging:
  level: info

resources:
  requests:
    cpu: 100m
    memory: 64M
  limits:
    cpu: 200m
    memory: 256M

vpa:
  enabled: true
  minAllowed:
    cpu: 100m
    memory: 64M
  updatePolicy:
    updateMode: "Auto"

webhookConfig:
  serverPort: 9443
  timeoutSeconds: 10
  failurePolicy: Ignore

healthPort: 8080
metricsPort: 8081

# policies:
#   etcd:
#     namespaceLabels: {}
#     podLabels:
#       app: etcd-statefulset
#       role: main
#     nodeLabels:
#       pool.worker.gardener.cloud/dedicated-for: etcd
#     tolerations:
#     - key: pool.worker.gardener.cloud/dedicated-for
#       operator: Equal
#       value: etcd
#       effect: NoExecute
#   fluent-bit:
#     namespaceLabels: {}
#     podLabels:
#       app: fluent-bit
#       role: logging
#       gardener.cloud/role: logging
#     tolerations:
#     - key: pool.worker.gardener.cloud/dedicated-for
#       operator: Equal
#       value: etcd
#       effect: NoExecute

gardener:
  version: ""
