{{- if .Values.vpa.enabled}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: {{ include "name" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- if .Values.vpa.minAllowed }}
  resourcePolicy:
    containerPolicies:
    - containerName: kupid
      minAllowed:
{{ toYaml .Values.vpa.minAllowed | indent 8 }}
{{- end }}
{{- end }}